// @generated by scripts/protocol_check.py --write
// Rust uprava-protocol enums are the source of truth for these wire literals.

export const AGENT_EXECUTION_PROFILE_VALUES = [
  "managed",
  "exec_compatibility",
] as const;

export const RUNTIME_ATTEMPT_STATE_VALUES = [
  "starting",
  "ready",
  "disconnected",
  "reconnecting",
  "recovered",
  "stopping",
  "stopped",
  "failed",
  "lost",
] as const;

export const PROVIDER_RUNTIME_CAPABILITY_VALUES = [
  "provider.codex.exec",
  "provider.codex.managed",
  "provider.codex.managed.approval",
  "provider.codex.managed.interrupt",
  "provider.codex.managed.resume",
] as const;

export const PROVIDER_INTERACTION_KIND_VALUES = [
  "approval",
  "user_input",
] as const;

export const PROVIDER_INTERACTION_STATE_VALUES = [
  "requested",
  "resolving",
  "approved",
  "denied",
  "answered",
  "expired",
  "cancelled",
  "superseded",
] as const;

export const RUNTIME_RECOVERY_STATUS_VALUES = [
  "not_required",
  "live",
  "reconnecting",
  "recovered",
  "provider_resumable",
  "degraded",
  "lost",
  "failed",
] as const;

export const ACTION_CAPABILITY_VALUES = [
  "session.attach",
  "session.detach",
  "session.sendTurn",
  "runtime.interrupt",
  "runtime.stop",
  "runtime.resume",
  "approval.resolve",
  "providerInteraction.submitInput",
  "warning.acknowledge",
  "reference.openInInspector",
  "reference.copy",
  "deduction.request",
] as const;

export const DEPLOYMENT_PROFILE_VALUES = ["controlled_dev"] as const;

export const NODE_PRESENCE_VALUES = [
  "reachable",
  "stale",
  "offline",
  "revoked",
] as const;

export const RUNTIME_SESSION_STATE_VALUES = [
  "starting",
  "ready",
  "running",
  "blocked",
  "stopping",
  "stopped",
  "interrupted",
  "resuming",
  "stale",
  "error",
  "expired",
] as const;

export const SESSION_THREAD_STATE_VALUES = [
  "created",
  "active",
  "detached",
  "stopped",
  "degraded",
] as const;

export const PLACEMENT_STATE_VALUES = [
  "pending",
  "validated",
  "missing",
  "read_only",
  "error",
] as const;

export const WARNING_SEVERITY_VALUES = [
  "info",
  "warning",
  "hard_block",
] as const;

export const CLIENT_LOG_LEVEL_VALUES = [
  "debug",
  "info",
  "warn",
  "error",
] as const;

export const COMMAND_STATE_VALUES = [
  "recorded",
  "pending_dispatch",
  "dispatched",
  "acknowledged",
  "completed",
  "failed",
  "blocked",
  "expired",
] as const;

export const COMMAND_KIND_VALUES = [
  "StartRuntime",
  "ResumeRuntime",
  "SendTurn",
  "ResolveApproval",
  "SubmitUserInput",
  "InterruptRuntime",
  "StopRuntime",
  "ValidateWorkspace",
  "RefreshResourceSnapshot",
  "ListWorkspaceTree",
  "ReadWorkspaceFile",
  "WriteWorkspaceFile",
  "RunWorkspaceCommand",
  "ReadWorkspaceDiff",
  "OpenWorkspaceTerminal",
  "AttachWorkspaceTerminal",
  "ResizeWorkspaceTerminal",
  "WriteWorkspaceTerminal",
  "CloseWorkspaceTerminal",
  "RequestDeduction",
  "CancelDeduction",
  "RunTask",
  "CancelTaskRun",
  "Tooling",
  "Extension",
] as const;

export const EVENT_KIND_VALUES = [
  "runtime.attempt.started",
  "runtime.attempt.ready",
  "runtime.attempt.disconnected",
  "runtime.attempt.reconnecting",
  "runtime.attempt.recovered",
  "runtime.attempt.failed",
  "runtime.starting",
  "runtime.ready",
  "runtime.running",
  "runtime.blocked",
  "runtime.expired",
  "runtime.resuming",
  "runtime.stopped",
  "runtime.error",
  "turn.started",
  "turn.completed",
  "turn.interrupted",
  "provider.activity",
  "provider.interaction.requested",
  "provider.interaction.resolved",
  "provider.output.delta",
  "provider.message.completed",
  "approval.requested",
  "approval.resolved",
  "runtime.policy.effective",
  "runtime.policy.override",
  "coordination.warning_acknowledged",
  "workspace.validated",
  "resource.snapshot.updated",
  "workspace.file.written",
  "workspace.command.completed",
  "workspace.check.completed",
  "workspace.diff.observed",
  "deduction.requested",
  "deduction.completed",
  "deduction.invalid",
  "deduction.failed",
  "deduction.cancelled",
  "task_run.state_changed",
  "extension",
] as const;

export const MESSAGE_ROLE_VALUES = [
  "user",
  "assistant",
  "system",
  "runtime",
  "approval",
] as const;

export const SCHEDULED_MESSAGE_STATE_VALUES = [
  "scheduled",
  "sending",
  "sent",
  "failed",
  "cancelled",
] as const;

export const WORKSPACE_ENTRY_KIND_VALUES = [
  "directory",
  "file",
  "symlink",
  "other",
] as const;

export const WORKSPACE_ENTRY_STATUS_VALUES = [
  "readable",
  "directory",
  "large",
  "binary",
  "ignored",
  "generated",
  "permission_denied",
  "outside_workspace",
  "missing",
  "not_file",
  "not_directory",
  "symlink",
  "error",
] as const;

export const WORKSPACE_ENTRY_CLASSIFICATION_VALUES = [
  "normal",
  "generated",
  "ignored",
] as const;

export const WORKSPACE_COMMAND_INTENT_VALUES = ["command", "check"] as const;

export const WORKSPACE_TERMINAL_STATE_VALUES = [
  "opening",
  "running",
  "detached",
  "exited",
  "closed",
  "error",
] as const;

export const WORKSPACE_TERMINAL_CLIENT_FRAME_KIND_VALUES = [
  "input",
  "resize",
  "close",
  "ping",
] as const;

export const WORKSPACE_TERMINAL_STREAM_FRAME_KIND_VALUES = [
  "output",
  "status",
  "pong",
  "error",
] as const;

export const TOOL_SOURCE_KIND_VALUES = [
  "uprava_native",
  "external_mcp",
  "plugin",
] as const;

export const TOOL_EXECUTION_KIND_VALUES = [
  "core_native",
  "node_native",
  "toolhive_mcp",
  "external_provider",
  "hybrid",
] as const;

export const TOOL_RISK_LEVEL_VALUES = [
  "read_only",
  "workspace_write",
  "external_read",
  "external_write",
  "credentialed_action",
  "destructive",
  "privileged_local",
  "network_broad",
] as const;

export const TOOL_DEFINITION_STATE_VALUES = [
  "active",
  "deprecated",
  "disabled",
] as const;

export const TOOL_AVAILABILITY_STATE_VALUES = [
  "available",
  "unavailable",
  "degraded",
  "approval_required",
] as const;

export const TOOL_UNAVAILABLE_REASON_VALUES = [
  "node_offline",
  "capability_missing",
  "dependency_missing",
  "dependency_unhealthy",
  "not_authenticated",
  "permission_denied",
  "policy_blocked",
  "project_not_enabled",
  "session_not_enabled",
  "schema_changed",
  "backend_unreachable",
  "toolhive_missing",
] as const;

export const OBSERVED_CAPABILITY_STATE_VALUES = [
  "available",
  "unavailable",
  "unknown",
] as const;

export const INTEGRATION_DESIRED_STATE_VALUES = [
  "enabled",
  "disabled",
] as const;

export const INTEGRATION_AUTH_STATE_VALUES = [
  "disconnected",
  "connecting",
  "connected",
  "expired",
  "error",
] as const;

export const MCP_DEPENDENCY_ACTUAL_STATE_VALUES = [
  "toolhive_missing",
  "missing_auth",
  "installing",
  "starting",
  "running",
  "degraded",
  "failed",
  "stopped",
] as const;

export const POLICY_DECISION_VALUES = [
  "allow",
  "deny",
  "require_approval",
] as const;

export const TOOL_CALL_STATE_VALUES = [
  "requested",
  "authorized",
  "approval_required",
  "started",
  "completed",
  "failed",
  "denied",
  "cancelled",
  "timed_out",
] as const;

export const TOOL_INVOCATION_MODE_VALUES = [
  "stable_execute_tool",
  "dynamic_mount_optional",
] as const;

export const TOOL_EXECUTION_ERROR_CODE_VALUES = [
  "invalid_arguments",
  "permission_denied",
  "approval_required",
  "unavailable",
  "schema_changed",
  "rate_limited",
  "request_too_large",
  "result_too_large",
  "timeout",
  "cancelled",
  "backend_failed",
  "toolhive_missing",
  "not_authenticated",
  "scope_mismatch",
  "lease_expired",
  "lease_revoked",
] as const;
